<?php 
require_once "/var/www/magento/app/Mage.php";
Varien_Profiler::enable();
Mage::setIsDeveloperMode(true);
ini_set('display_errors', 1);
umask(0);
Mage::app('default');

function createCustomer($custVal){
	$value = '';
	//$custVals = array_pop($custVal);
	foreach($custVal as $customerVal){
		$customer_email = $customerVal[0];  // email address that will pass by the questionaire 
		$customer_fname = $customerVal[1];      // we can set a tempory firstname here 
		$customer_lname = $customerVal[2];      // we can set a tempory lastname here 
		$customer_password = $customerVal[3];                    // the lenght of autogenerated password
		$customer_gender = $customerVal[4];                    // the lenght of autogenerated password

		$customer = Mage::getModel('customer/customer');
		//$customer->store = 1;
		$customer->setWebsiteId(Mage::app()->getWebsite()->getId());
		$customer->loadByEmail($customer_email);

		// Check if the email exist on the system.
		//If YES,  it will not create a user account. 

		if(!$customer->getId()) {
			//setting data such as email, firstname, lastname, and password 
			$customer->setEmail($customer_email); 
			$customer->setFirstname($customer_fname);
			$customer->setLastname($customer_lname);
			//$customer->setIs_dealer_agent('1');
			$customer->setGender(Mage::getResourceModel('customer/customer')
					->getAttribute('gender')
					->getSource()
					->getOptionId($customer_gender));
			//  $customer->setPassword($customer->generatePassword($customer_password));
			$customer->setPassword($customer_password);
		}else{
			$value .=  "\t Customer already exist with same email-id : ".$customer_email."</br>";
		}
		try{
			//the save the data and send the new account email.
			$customer->setGroupId(3);
			$customer->setWebsiteId(3);
			$customer->save();
			//$customer->setConfirmation(null);
			//$customer->save(); 
			//$customer->sendNewAccountEmail();
			$value .= "New customer created with email-id : <b>".$customer_email."</b></br>";
		}catch(Exception $ex){
			$value .= "<b>Unable to save customer - Magento Error below</b>"."</br>".$ex; 
		}
	}
	return $value;
}
?>
