<?php
require_once "/var/www/magento/app/Mage.php";
Varien_Profiler::enable();
Mage::setIsDeveloperMode(true);
ini_set('display_errors', 1);
umask(0);
Mage::app('default');

$customer_email = $argv[1];  // email adress that will pass by the questionaire 
$customer_fname = $argv[2];      // we can set a tempory firstname here 
$customer_lname = $argv[3];       // we can set a tempory lastname here 
$customer_password = $argv[4];                    // the lenght of autogenerated password

$customer = Mage::getModel('customer/customer');
//$customer->store = 1;
$customer->setWebsiteId(Mage::app()->getWebsite()->getId());
$customer->loadByEmail($customer_email);
/*
* Check if the email exist on the system.
* If YES,  it will not create a user account. 
*/

if(!$customer->getId()) {
	//setting data such as email, firstname, lastname, and password 
	$customer->setEmail($customer_email); 
	$customer->setFirstname($customer_fname);
	$customer->setLastname($customer_lname);
	$customer->setGender(Mage::getResourceModel('customer/customer')
            ->getAttribute('gender')
            ->getSource()
            ->getOptionId('Male'));
	//  $customer->setPassword($customer->generatePassword($customer_password));
	$customer->setPassword($customer_password);
	echo "New customer created with email-id : ".$customer_email."\n";
}else{
	echo "\t Customer already exist with same email-id : ".$customer_email."\n";
}
try{
	//the save the data and send the new account email.
	$customer->setGroupId(3);
	$customer->setWebsiteId(3);
	$customer->save();
	//$customer->setConfirmation(null);
	//$customer->save(); 
	//$customer->sendNewAccountEmail();
}catch(Exception $ex){
	echo "Unable to save customer.".$ex; 
}
?>
