<?php
require_once "/var/www/magento/app/Mage.php";
Varien_Profiler::enable();
Mage::setIsDeveloperMode(true);
ini_set('display_errors', 1);
umask(0);

Mage::app('default');

$customer_email = $argv[1];  // email adress that will pass by the questionaire 
$customer_fname = $argv[3];      // we can set a tempory firstname here 
$customer_lname = $argv[4];       // we can set a tempory lastname here 
$customer_password = $argv[2];                    // the lenght of autogenerated password

$customer = Mage::getModel('customer/customer');
$customer->setWebsiteId(Mage::app()->getWebsite()->getId());
$customer->loadByEmail($customer_email);
/*
* Check if the email exist on the system.
* If YES,  it will not create a user account. 
*/

if($customer->getId()) {

   //setting data such as email, firstname, lastname, and password 

//  $customer->setEmail($customer_email); 
//  $customer->setFirstname($customer_fname);
//  $customer->setLastname($customer_lname);
//  $customer->setPassword($customer->generatePassword($customer_password));
//  $customer->setPassword($customer_password);
	echo "Hello.. Your request is in process...\n";
	$customer->setFirstname($customer_fname);
	$customer->setLastname($customer_lname);
	$customer->setPassword($customer_password);
	//echo "Customer name is - "." $customer_fname"." $customer_lname \n";
	try{
	$customer->save();
	echo "Customer edited sucessfully. \n";
	}catch(exception $e) {echo "Unable to save customer, reason below- \n";}

}else{
	echo "Customer does't exist with email-id : ".$customer_email."\n";
}
?>
